stages:
  - build
  - deploy

back:build-and-deploy:
  stage: build
  image:  ubuntu:latest
  script:
    - echo "Running script..."
    - cd .infra
    - chmod +x dh-backend-dev.pem
    - ssh -i "dh-backend-dev.pem" ec2-user@ec2-54-177-126-226.us-west-1.compute.amazonaws.com 'sh dh-recipes/DH-ProyectoIntegrador2/.infra/build-and-run.sh && exit'
    - echo "Deployed..."

front:build:
  stage: build
  image:  node:20
  variables:
    NODE_OPTIONS: --max_old_space_size=4096
  script:
    - echo "Building app..."
    - echo "VITE_GATEWAY_URL=http://${DEPLOY_SERVER_IP}:8090" > frontend/.env
    - cd frontend
    - echo "Deleting modules..."
    - rm -rf node_modules
    - echo "Pruning modules..."
    - npm prune
    - echo "Running npm install..."
    - npm install
    - echo "Minifying artifacto for deployment..."
    - npm run build
    - echo "Finished building the app."
  artifacts:
    expire_in: 1 week
    paths:
      - frontend/dist/*

front:deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  before_script:
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  script:
    - echo "Deploying started..."
    - aws s3 sync front/dist/ s3://$S3_BUCKET_NAME
    - echo "Finished deploying the app."
  only:
    - Develop