eureka:
    client:
        service-url:
            defaultZone: http://${LOCAL_HOST:localhost}:8761/eureka
    instance:
        hostname: ${LOCAL_HOST:localhost}
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
    application:
        name: pi2
        security:
            oauth2:
                resourceserver:
                    jwt:
                        issuer-uri: http://${LOCAL_HOST:localhost}:8089/realms/proyecto-integrador
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_ID:localhost}:3306/MealMap?createDatabaseIfNotExist=true
        password: ${MYSQL_PASSWORD:root}
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
server:
    port: ${PORT:8080}