eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
    application:
        name: pi2
        security:
            oauth2:
                resourceserver:
                    jwt:
                        issuer-uri: http://localhost:8089/realms/proyecto-integrador
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/MealMap?createDatabaseIfNotExist=true
        password: root
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true