spring:
  application:
    name: ms-users
  security:
  oauth2:
    client:
      provider:
        users-service:
          token-uri: http://${KEYCLOAK_HOST:localhost}:8089/realms/proyecto-integrador/protocol/openid-connect/token
      registration:
        users-service:
          client-id: ms-users
          client-secret: ${CLIENT_SECRET}
          scope:
            - openid
          authorization-grant-type: client_credentials

eureka:
  instance:
    hostname: ${LOCAL_HOST:localhost}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://${LOCAL_HOST:localhost}:8761/eureka

server:
  port: ${PORT:0}

keycloakProperties:
  serverUrl: http://${KEYCLOAK_HOST:localhost}:8089/
  realm: proyecto-integrador
  clientId: ms-users
  clientIdFront: frontend
  clientSecret: ${CLIENT_SECRET}
