# Configuraciones del servidor
server:
  port: 8090
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# Configuraciones de spring cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters: TokenRelay
      routes:
        - id: mealmap-core
          uri: lb://pi2
          predicates:
            - Path=/api/v1/categories/**, /api/v1/ingredient/**, /api/v1/recipes/**, /api/v1/favorites/**
          filters:
            - StripPrefix=2
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2



  # Configuraciones de seguridad
  security:
    oauth2:
      client:
        provider:
          gateway-service:
            issuer-uri: http://localhost:8089/realms/proyecto-integrador
        registration:
          gateway-service:
            client-id: ms-gateway
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/proyecto-integrador