spring:
  application:
    name: servicio-eureka-server

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${LOCAL_HOST:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false